# Generated by Django 5.1.6 on 2025-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_food_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
