# Generated by Django 5.1.6 on 2025-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_food_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
