# Generated by Django 5.1.6 on 2025-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
